services:
  cloudflared:
    image: 'cloudflare/cloudflared:2024.5.0'
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
networks:
  default:
    name: "tunnel_net"
    external: true
